### ISSUE TITLE
Switch out the API urls

### ISSUE THREAD

**Issue by willmot** [humanmade/godaddy-forms-wordpress-plugin#4]
We'll likely want to switch out the Mad Mimi API with the new GoDaddy ones

**Comment by willmot** [comment]
@susandyoung is this something you're able to provide?

**Comment by susandyoung** [comment]
@willmot I will get this for you.

**Comment by susandyoung** [comment]
@willmot Actually, the Mimi URLs will work just fine for the GEM plugin. They're actually the same app on the backend running under different branding. I just double checked about the API URLs.

**Comment by willmot** [comment]
Ok great, thanks!
